apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  containers:
    - env:
        - name: KAFKA_BROKERCONNECT
          value: kafka-1:29092,kafka-2:29093
        - name: SCHEMAREGISTRY_CONNECT
          value: http://schema-registry:8081
      image: obsidiandynamics/kafdrop
      name: kafdrop
      ports:
        - containerPort: 9000
          protocol: TCP
  restartPolicy: Never
