apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: kafka-2
  name: kafka-2
spec:
  containers:
    - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://:29093,EXTERNAL://localhost:9093
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_LISTENERS
          value: INTERNAL://:29093,EXTERNAL://:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
      image: wurstmeister/kafka:latest
      name: kafka-2
      ports:
        - containerPort: 9093
          protocol: TCP
  restartPolicy: Never
